name: CI
on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: nikhilgadge/vidly-frontend:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "BASE_URL=http://35.91.70.217:3001"

      - name: SSH to EC2 to deploy stack 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                sed -i 's|image: nikhilgadge/vidly-frontend:.*|image: '"nikhilgadge/vidly-fronttend:${{ github.run_id }}"'|' /home/ec2-user/deploy/docker-compose.prod.yml
    
                cat /home/ec2-user/deploy/docker-compose.prod.yml # Optional: print the file to check the changes
                docker stack deploy -c /home/ec2-user/deploy/docker-compose.prod.yml vidly
      


  

  
          
