name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  build-test: 
    runs-on: ubuntu-latest
    
      
    steps:
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "14.16.0"
        
    
      - name: Checkout
        uses: actions/checkout@v2
    

      - name: build
        run: npm start

      - name: test
        run: npm run test

      
        
          