name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  build-test: 
    runs-on: ubuntu-latest
    
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: docker-compose up -d

      - name: test
        run: docker-compose run -e CI=true --rm frontend npm run test 

      - name: clear
        run: docker-compose down

      
        
          